version: "3"

tasks:
  install:
    cmds:
      - poetry install
  lint:
    cmds:
      - poetry run flake8 .
  format:
    cmds:
      - poetry run black .
  dev:
    cmds:
      - poetry run uvicorn src.main:app --reload --log-level debug
  run:
    cmds:
      - poetry run uvicorn src.main:app --port 8004 --no-access-log
  setup:
    cmds:
      - curl -sSL https://install.python-poetry.org | python3 -
