[package]
name = "async-graphql-test"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "4.0.15"
async-graphql-axum = "4.0.15"
axum = "0.5.16"
futures-util = "0.3.24"
slab = "0.4.7"
tokio = { version = "1.21.2", features = ["full"] }
