name: build-run
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
      - run: echo "./bin" >> $GITHUB_PATH
      - run: echo "~/go/bin" >> $GITHUB_PATH
      - run: export PATH=$PATH:~/go/bin && task install-ci
      - run: export PATH=$PATH:~/go/bin && task ci
      - run: export PATH=$PATH:~/go/bin && task citest
